ToDoApp/ToDoApp/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
    }
}

ToDoApp/ToDoApp/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public class Note : BaseModel
    {
        [Required]
        [StringLength(60, MinimumLength = 5)]
        public string Title { get; set; }

        [StringLength(100)]
        public string Description { get; set; }

        [Display(Name = "Is Done")]
        public bool IsDone { get; set; }
    }
}

ToDoApp/ToDoApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

ToDoApp/ToDoApp/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoApp.DataAccess;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class NotesController : Controller
    {
       
        public ActionResult Index()
        {
            NoteRepository repo = new NoteRepository();
            List<Note> model = repo.GetAll();

            return View(model);
        }

        [HttpPost]
        public ActionResult Action(int id)
        {

            NoteRepository repo = new NoteRepository();
            Note note = repo.Get(id);
            note.IsDone = true;
            repo.Update(note);

            return View(note);
        }

        public JsonResult GetNotes()
        {
            NoteRepository repo = new NoteRepository();
            List<Note> Notes = repo.GetAll();
            return Json(Notes, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            NoteRepository repo = new NoteRepository();
            Note note = repo.Get(id);

            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Note model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            NoteRepository repository = new NoteRepository();
            repository.Insert(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            NoteRepository repository = new NoteRepository();
            Note model = repository.Get(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Note model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            NoteRepository repository = new NoteRepository();
            repository.Update(model);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            NoteRepository repository = new NoteRepository();
            Note model = repository.Get(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NoteRepository repository = new NoteRepository();
            Note note = repository.Get(id);

            if (ModelState.IsValid)
            {
                repository.Delete(note);

                return RedirectToAction("Index");
            }

            return View(note);
        }
    }
}

ToDoApp/ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - To Do App</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("To Do App", "Index", "Notes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
 
</body>
</html>